openapi: 3.1.0
info:
  title: NeuroViz - OpenAPI 3.1
  version: 1.0.0
# tags:
#   - name: pet
#     description: Everything about your Pets
#     externalDocs:
#       description: Find out more
#       url: http://swagger.io
#   - name: store
#     description: Access to Petstore orders
#     externalDocs:
#       description: Find out more about our store
#       url: http://swagger.io
#   - name: user
#     description: Operations about user
paths:
  /heartbeat:
    post:
      summary: Send a heartbeat to notify the server that the client is still alive
      operationId: heartbeat
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Heartbeat"
        required: true
      responses:
        "200":
          description: Successful operation

components:
  schemas:
    Heartbeat:
      type: object
      properties:
        device:
          type: string
          example: "XReal Air 2"
  # requestBodies:
  #   Pet:
  #     description: Pet object that needs to be added to the store
  #     content:
  #       application/json:
  #         schema:
  #           $ref: "#/components/schemas/Pet"
  #       application/xml:
  #         schema:
  #           $ref: "#/components/schemas/Pet"
  #   UserArray:
  #     description: List of user object
  #     content:
  #       application/json:
  #         schema:
  #           type: array
  #           items:
  #             $ref: "#/components/schemas/User"

  securitySchemes:
    auth: # arbitrary name for the security scheme
      type: http
      scheme: bearer

security:
  - auth: [] # use the same name as above
