
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Set a parameter in live view
 */
async setParam(parameter: RenderParameter, value: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_param", { parameter, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a parameter in live view
 */
async getParam(parameter: RenderParameter) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_param", { parameter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIpAddress() : Promise<string> {
    return await TAURI_INVOKE("get_ip_address");
},
/**
 * List all presets
 */
async listPresets() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_presets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve a preset by file name
 */
async getPreset(sluggedPresetName: string) : Promise<Result<Preset, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_preset", { sluggedPresetName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save current live parameters to a preset
 */
async createPreset(presetName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_preset", { presetName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve a preset
 */
async getExperiment(sluggedName: string) : Promise<Result<Experiment, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_experiment", { sluggedName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new experiment
 */
async createExperiment(experimentInitData: CreateExperiment) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_experiment", { experimentInitData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all experiments
 */
async listExperiments() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_experiments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start an experiment
 */
async getAllExperiments() : Promise<Result<Experiment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_experiments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startExperiment(sluggedExperimentName: string, obeserverId: number, note: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_experiment", { sluggedExperimentName, obeserverId, note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
connectionEvent: ConnectionEvent,
stateEvent: StateEvent
}>({
connectionEvent: "connection-event",
stateEvent: "state-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AppState = { LiveView: RenderParameters } | { Experiment: ExperimentState }
export type Choice = { a: string; b: string }
export type ConnectionEvent = { is_connected: boolean }
export type CreateExperiment = (
/**
 * Rating between 1-5
 */
{ experiment_type: "rating"; order: string[] } | 
/**
 * Choose between two options
 */
{ experiment_type: "choice"; choices: Choice[] }) & { name: string; presets: string[] }
export type CurrentPreset = "A" | "B"
export type Experiment = (
/**
 * Rating between 1-5
 */
{ experiment_type: "rating"; order: string[] } | 
/**
 * Choose between two options
 */
{ experiment_type: "choice"; choices: Choice[] }) & { name: string; presets: Partial<{ [key in string]: Preset }> }
export type ExperimentResult = ({ experiment_type: "rating"; ratings: OutcomeRating[] } | { experiment_type: "choice"; choices: OutcomeChoice[] }) & { name: string; time: string; observer_id: number; note: string; presets: Partial<{ [key in string]: Preset }> }
export type ExperimentState = { experiment: Experiment; experiment_result: ExperimentResult; current_index: number; choice_current_preset: CurrentPreset }
export type OutcomeChoice = { a: string; b: string; selected: string; time: string; duration_on_a: number; duration_on_b: number; duration: number }
export type OutcomeRating = { preset: string; rank: number; time: string; duration: number }
export type Preset = { name: string; parameters: RenderParameters }
export type RenderParameter = "Hue" | "Smoothness" | "Metallic" | "Emission"
export type RenderParameters = { hue: number; smoothness: number; metallic: number; emission: number }
export type StateEvent = { state: AppState }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
