name: Unity

# on:
#   push:
#     branches: ["main"]
# TODO remove
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v3
        with:
          path: mobile/Library
          key: Library-${{ hashFiles('mobile/Assets/**', 'mobile/Packages/**', 'mobile/ProjectSettings/**') }}
          restore-keys: |
            Library-
              githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          projectPath: mobile

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
